services:
  postgres:
    image: postgis/postgis:latest
    container_name: urban-heat-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: urban_heat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: